[workspace]
authors = ["Jacob Van Meter <jacobvm04@gmail.com>"]
channels = ["robostack-humble", "conda-forge"]
name = "slam"
platforms = ["osx-arm64", "linux-aarch64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]

[dependencies]
python = ">=3.11,<3.12"
pip = ">=25.2,<26"
hydra-core = ">=1.3.2,<2"
rerun-sdk = ">=0.27, <0.28"
cmake = ">=4.2.0,<5"
ninja = ">=1.13.2,<2"
pybind11 = ">=3.0.1,<4"
pillow = ">=9.1, <11"
opencv = ">=4.11.0,<5"
compilers = ">=1.11.0,<2"

[feature.ros2.dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"

[pypi-dependencies]
gtsam-develop = ">=4.3a0.dev202510200041, <5"
opencv-python-headless = ">=4, <5"
tqdm = ">=4.66.0, <5"
auditwheel = ">=6.0.0, <7"
patchelf = ">=0.17.0, <1"
delocate = ">=0.12.0, <1"
line_profiler = ">=5.0.0, <6"
pillow = ">=9.1, <11"
term-image = ">=0.7.0, <0.8"
slam = { path = ".", editable = true }
eclipse-zenoh = ">=1.7.0, <2"
pydantic = ">=2.12.5, <3"

[feature.dev.pypi-dependencies]
ipykernel = ">=7.1.0, <8"
matplotlib = ">=3.10.7, <4"

[feature.ros2.pypi-dependencies]
rosbags = ">=0.11.0, <0.12"
rosbags-image = ">=0.10.3, <0.11"

[environments.dev]
features = ["dev"]

[environments.ros2]
features = ["ros2"]

[environments.ros2-dev]
features = ["ros2", "dev"]

[environments]
default = []

[package]
name = "slam"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-python", version = "==0.4.0" }

[package.host-dependencies]
hatchling = "==1.26.3"

[package.run-dependencies]
python = ">=3.11,<3.12"
hydra-core = ">=1.3.2,<2"
gtsam-develop = ">=4.3a0.dev202510200041, <5"
opencv-python-headless = ">=4, <5"
rerun-sdk = ">=0.27, <0.28"
tqdm = ">=4.66.0, <5"
pillow = ">=9.1, <11"
term-image = ">=0.7.0, <0.8"

[tasks.build]
cmd = "rm -rf build && pixi build"

[tasks.euroc]
cmd = "cd tests && python vio_example_euroc.py"
depends-on = ["build"]

# TODO: add a test script that creates a virtual environment and installs the wheel and runs the tests/examples to verify the wheel works.
# also support using conda packages
[tasks.wheel-jetson]
cmd = """
rm -rf dist build && \
OpenCV_DIR=/usr/lib/cmake/opencv4 SLAM_BUILD_VARIANT=jetson uv build --wheel && \
auditwheel repair dist/*.whl --plat manylinux_2_35_aarch64 -w dist/ && \
rm -f dist/*-linux_aarch64.whl && \
echo 'Built:' && ls dist/*.whl
"""
description = "Build Jetson wheel using system compiler + system OpenCV"

[tasks.wheel-macos]
cmd = """
rm -rf dist build && \
SLAM_BUILD_VARIANT=macos uv build --wheel && \
delocate-wheel -v --exclude /opt/homebrew dist/*.whl && \
echo 'Built:' && ls dist/*.whl
"""
description = "Build portable macOS wheel with bundled dependencies"
