[workspace]
authors = ["Jacob Van Meter <jacobvm04@gmail.com>"]
channels = ["conda-forge"]
name = "slam"
platforms = ["linux-aarch64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.10,<3.11"
pip = ">=25.2,<26"
hydra-core = ">=1.3.2,<2"

[pypi-dependencies]
gtsam-develop = ">=4.3a0.dev202510200041, <5"
opencv-python-headless = ">=4.12.0.88, <5"
rerun-sdk = ">=0.27.2, <0.28"
tqdm = ">=4.66.0, <5"

[feature.dev.pypi-dependencies]
ipykernel = ">=7.1.0, <8"
matplotlib = ">=3.10.7, <4"

[environments.dev]
features = ["dev"]
